import type {
  City,
  Country,
  EducationTrack,
  Industry,
  JobListing,
  PolicyVector,
  SkillId,
} from "./types";

export const SKILLS: { id: SkillId; name: string; group: string }[] = [
  { id: "programming", name: "Programming", group: "Technical" },
  { id: "ai", name: "Artificial Intelligence", group: "Technical" },
  { id: "ml", name: "Machine Learning", group: "Technical" },
  { id: "cybersecurity", name: "Cybersecurity", group: "Technical" },
  { id: "engineering", name: "Engineering", group: "Technical" },
  { id: "data", name: "Data Analysis", group: "Technical" },
  { id: "robotics", name: "Robotics", group: "Technical" },
  { id: "math", name: "Mathematics", group: "Technical" },
  { id: "sales", name: "Sales", group: "Business" },
  { id: "marketing", name: "Marketing", group: "Business" },
  { id: "accounting", name: "Accounting", group: "Business" },
  { id: "finance", name: "Finance", group: "Business" },
  { id: "management", name: "Management", group: "Business" },
  { id: "operations", name: "Operations", group: "Business" },
  { id: "negotiation", name: "Negotiation", group: "Business" },
  { id: "entrepreneurship", name: "Entrepreneurship", group: "Business" },
  { id: "speaking", name: "Public Speaking", group: "Public" },
  { id: "writing", name: "Writing", group: "Public" },
  { id: "journalism", name: "Journalism", group: "Public" },
  { id: "politics", name: "Politics", group: "Public" },
  { id: "leadership", name: "Leadership", group: "Public" },
  { id: "diplomacy", name: "Diplomacy", group: "Public" },
  { id: "construction", name: "Construction", group: "Practical" },
  { id: "realestate", name: "Real Estate", group: "Practical" },
  { id: "manufacturing", name: "Manufacturing", group: "Practical" },
  { id: "logistics", name: "Logistics", group: "Practical" },
];

export const TRACKS: { id: EducationTrack; name: string; skills: SkillId[] }[] = [
  { id: "general", name: "General Studies", skills: ["writing", "math"] },
  { id: "computer_science", name: "Computer Science", skills: ["programming", "math", "data"] },
  { id: "ai", name: "Artificial Intelligence", skills: ["ai", "ml", "programming", "math"] },
  { id: "engineering", name: "Engineering", skills: ["engineering", "math", "manufacturing"] },
  { id: "finance", name: "Finance", skills: ["finance", "accounting", "math"] },
  { id: "economics", name: "Economics", skills: ["finance", "data", "math"] },
  { id: "law", name: "Law", skills: ["writing", "negotiation", "politics"] },
  { id: "medicine", name: "Medicine", skills: ["data", "leadership"] },
  { id: "business", name: "Business", skills: ["management", "sales", "entrepreneurship"] },
  { id: "marketing", name: "Marketing", skills: ["marketing", "writing", "sales"] },
  { id: "design", name: "Design", skills: ["marketing", "writing"] },
  { id: "government", name: "Public Policy", skills: ["politics", "diplomacy", "leadership"] },
  { id: "journalism", name: "Journalism", skills: ["journalism", "writing", "speaking"] },
  { id: "real_estate", name: "Real Estate", skills: ["realestate", "negotiation", "finance"] },
  { id: "science", name: "Science", skills: ["math", "data", "engineering"] },
  { id: "vocational", name: "Vocational", skills: ["construction", "manufacturing", "logistics"] },
];

export const INDUSTRIES: {
  id: Industry;
  name: string;
  pe: number;
  wage: number;
  cyclical: number;
  aiExpose: number;
  skills: SkillId[];
}[] = [
  { id: "technology", name: "Technology", pe: 28, wage: 1.4, cyclical: 0.8, aiExpose: 0.4, skills: ["programming", "management"] },
  { id: "ai", name: "Artificial Intelligence", pe: 42, wage: 1.8, cyclical: 0.7, aiExpose: -0.4, skills: ["ai", "ml", "programming"] },
  { id: "software", name: "Software", pe: 30, wage: 1.5, cyclical: 0.7, aiExpose: 0.3, skills: ["programming", "management"] },
  { id: "gaming", name: "Gaming", pe: 26, wage: 1.2, cyclical: 0.6, aiExpose: 0.2, skills: ["programming", "marketing"] },
  { id: "retail", name: "Retail", pe: 16, wage: 0.7, cyclical: 1.2, aiExpose: 0.6, skills: ["sales", "operations"] },
  { id: "ecommerce", name: "E-commerce", pe: 24, wage: 1.1, cyclical: 0.9, aiExpose: 0.3, skills: ["marketing", "logistics"] },
  { id: "restaurants", name: "Restaurants", pe: 14, wage: 0.6, cyclical: 1.1, aiExpose: 0.3, skills: ["operations", "sales"] },
  { id: "hotels", name: "Hotels", pe: 18, wage: 0.8, cyclical: 1.3, aiExpose: 0.25, skills: ["operations", "management"] },
  { id: "construction", name: "Construction", pe: 12, wage: 0.9, cyclical: 1.5, aiExpose: 0.2, skills: ["construction", "operations"] },
  { id: "manufacturing", name: "Manufacturing", pe: 14, wage: 0.95, cyclical: 1.2, aiExpose: 0.55, skills: ["manufacturing", "operations"] },
  { id: "logistics", name: "Logistics", pe: 15, wage: 0.85, cyclical: 1.1, aiExpose: 0.4, skills: ["logistics", "operations"] },
  { id: "energy", name: "Energy", pe: 11, wage: 1.3, cyclical: 1.0, aiExpose: 0.15, skills: ["engineering", "operations"] },
  { id: "agriculture", name: "Agriculture", pe: 10, wage: 0.55, cyclical: 0.8, aiExpose: 0.35, skills: ["operations", "logistics"] },
  { id: "education", name: "Education", pe: 18, wage: 0.9, cyclical: 0.4, aiExpose: 0.45, skills: ["writing", "speaking"] },
  { id: "media", name: "Media", pe: 20, wage: 1.0, cyclical: 0.9, aiExpose: 0.5, skills: ["journalism", "writing"] },
  { id: "advertising", name: "Advertising", pe: 17, wage: 1.05, cyclical: 1.1, aiExpose: 0.55, skills: ["marketing", "writing"] },
  { id: "finance", name: "Finance", pe: 15, wage: 1.6, cyclical: 1.2, aiExpose: 0.5, skills: ["finance", "math"] },
  { id: "insurance", name: "Insurance", pe: 12, wage: 1.2, cyclical: 0.6, aiExpose: 0.45, skills: ["finance", "data"] },
  { id: "banking", name: "Banking", pe: 11, wage: 1.35, cyclical: 1.1, aiExpose: 0.5, skills: ["finance", "accounting"] },
  { id: "realestate", name: "Real Estate", pe: 13, wage: 1.1, cyclical: 1.4, aiExpose: 0.2, skills: ["realestate", "negotiation"] },
  { id: "entertainment", name: "Entertainment", pe: 22, wage: 0.95, cyclical: 1.0, aiExpose: 0.3, skills: ["marketing", "speaking"] },
  { id: "healthcare", name: "Healthcare", pe: 21, wage: 1.45, cyclical: 0.3, aiExpose: 0.25, skills: ["data", "leadership"] },
  { id: "legal", name: "Legal", pe: 16, wage: 1.5, cyclical: 0.5, aiExpose: 0.35, skills: ["writing", "negotiation"] },
  { id: "cybersecurity", name: "Cybersecurity", pe: 32, wage: 1.7, cyclical: 0.5, aiExpose: -0.1, skills: ["cybersecurity", "programming"] },
  { id: "robotics", name: "Robotics", pe: 34, wage: 1.55, cyclical: 0.8, aiExpose: -0.2, skills: ["robotics", "engineering"] },
  { id: "telecom", name: "Telecom", pe: 13, wage: 1.15, cyclical: 0.6, aiExpose: 0.3, skills: ["engineering", "operations"] },
  { id: "mining", name: "Mining", pe: 9, wage: 1.2, cyclical: 1.3, aiExpose: 0.25, skills: ["engineering", "operations"] },
  { id: "tourism", name: "Tourism", pe: 16, wage: 0.7, cyclical: 1.4, aiExpose: 0.2, skills: ["sales", "operations"] },
  { id: "casino", name: "Gaming Houses", pe: 14, wage: 0.85, cyclical: 1.1, aiExpose: 0.15, skills: ["operations", "management"] },
  { id: "research", name: "Research", pe: 25, wage: 1.25, cyclical: 0.4, aiExpose: -0.1, skills: ["math", "data"] },
];

export function industryMeta(id: Industry) {
  return INDUSTRIES.find((i) => i.id === id) ?? INDUSTRIES[0]!;
}

const centrist = (): PolicyVector => ({
  tax: 50,
  welfare: 50,
  business: 50,
  education: 55,
  healthcare: 55,
  housing: 50,
  technology: 55,
  infrastructure: 55,
  environment: 50,
  crime: 50,
  immigration: 50,
  trade: 55,
  spending: 50,
});

export const COUNTRY_DEFS: Omit<Country, "relations" | "cycle" | "revenue" | "spending" | "approval">[] = [
  {
    id: "indara",
    name: "Republic of Indara",
    adjective: "Indaran",
    capital: "Navpura",
    currency: { code: "INR", name: "Indaran Rupee", symbol: "₹" },
    fx: 1,
    government: "parliamentary",
    population: 428_000_000,
    gdp: 3.9e14,
    gdpGrowth: 6.1,
    inflation: 4.8,
    interestRate: 6.5,
    unemployment: 7.2,
    corpTax: 25,
    incomeTax: 30,
    propertyTax: 1.1,
    vat: 18,
    debt: 2.2e14,
    techLevel: 62,
    aiAdoption: 28,
    infrastructure: 58,
    educationIndex: 61,
    healthcareIndex: 55,
    housingIndex: 52,
    businessFreedom: 64,
    crimeIndex: 42,
    tariff: 8,
    tradeBalance: -1.2e13,
    policy: { ...centrist(), technology: 68, business: 62, welfare: 48 },
    rulingPartyId: "indara_unity",
    headOfGov: "Meera Halder",
    electionYear: 2029,
    conMember: true,
    councilSeat: true,
    blocs: ["Monsoon Compact", "South Arc"],
    color: "#e8b86d",
    map: { x: 52, y: 42, w: 16, h: 14 },
  },
  {
    id: "aurelia",
    name: "Commonwealth of Aurelia",
    adjective: "Aurelian",
    capital: "Lumen",
    currency: { code: "AUR", name: "Aurel", symbol: "₳" },
    fx: 84,
    government: "presidential",
    population: 68_000_000,
    gdp: 2.8e14,
    gdpGrowth: 2.1,
    inflation: 2.4,
    interestRate: 4.25,
    unemployment: 4.6,
    corpTax: 21,
    incomeTax: 32,
    propertyTax: 1.4,
    vat: 10,
    debt: 2.4e14,
    techLevel: 88,
    aiAdoption: 54,
    infrastructure: 86,
    educationIndex: 84,
    healthcareIndex: 78,
    housingIndex: 70,
    businessFreedom: 82,
    crimeIndex: 28,
    tariff: 3,
    tradeBalance: 4.1e12,
    policy: { ...centrist(), business: 70, technology: 80, tax: 42 },
    rulingPartyId: "aurelia_horizon",
    headOfGov: "Julian Voss",
    electionYear: 2028,
    conMember: true,
    councilSeat: true,
    blocs: ["Atlantic Ring", "Tech Accord"],
    color: "#6ea8ff",
    map: { x: 14, y: 28, w: 14, h: 12 },
  },
  {
    id: "vardania",
    name: "Vardan Federation",
    adjective: "Vardan",
    capital: "Kestrel",
    currency: { code: "VRD", name: "Vardan Mark", symbol: "₫" },
    fx: 18,
    government: "federation",
    population: 92_000_000,
    gdp: 1.1e14,
    gdpGrowth: 4.4,
    inflation: 6.2,
    interestRate: 8.0,
    unemployment: 9.1,
    corpTax: 22,
    incomeTax: 24,
    propertyTax: 0.8,
    vat: 12,
    debt: 4.8e13,
    techLevel: 51,
    aiAdoption: 16,
    infrastructure: 49,
    educationIndex: 54,
    healthcareIndex: 47,
    housingIndex: 50,
    businessFreedom: 58,
    crimeIndex: 48,
    tariff: 11,
    tradeBalance: 2.2e12,
    policy: { ...centrist(), business: 60, infrastructure: 70, tax: 40 },
    rulingPartyId: "vardania_forge",
    headOfGov: "Anton Reznik",
    electionYear: 2027,
    conMember: true,
    councilSeat: false,
    blocs: ["Heartland Pact"],
    color: "#d97757",
    map: { x: 34, y: 22, w: 14, h: 11 },
  },
  {
    id: "nordmark",
    name: "Kingdom of Nordmark",
    adjective: "Nordmarker",
    capital: "Havnstad",
    currency: { code: "NMK", name: "Nordmark Krona", symbol: "kr" },
    fx: 7.4,
    government: "monarchy",
    population: 12_400_000,
    gdp: 7.2e13,
    gdpGrowth: 1.6,
    inflation: 1.9,
    interestRate: 3.1,
    unemployment: 4.1,
    corpTax: 28,
    incomeTax: 42,
    propertyTax: 1.8,
    vat: 24,
    debt: 2.6e13,
    techLevel: 86,
    aiAdoption: 48,
    infrastructure: 91,
    educationIndex: 92,
    healthcareIndex: 94,
    housingIndex: 74,
    businessFreedom: 72,
    crimeIndex: 16,
    tariff: 4,
    tradeBalance: 1.8e12,
    policy: { ...centrist(), welfare: 82, tax: 72, environment: 80, healthcare: 88 },
    rulingPartyId: "nordmark_civic",
    headOfGov: "Elsa Lindholm",
    electionYear: 2027,
    conMember: true,
    councilSeat: true,
    blocs: ["Aurora League", "Green Compact"],
    color: "#7dd3c7",
    map: { x: 40, y: 8, w: 12, h: 9 },
  },
  {
    id: "zhenhua",
    name: "Zhenhua Union",
    adjective: "Zhenhuan",
    capital: "Dongcheng",
    currency: { code: "ZHN", name: "Zhenhua Yuan", symbol: "¥" },
    fx: 12.2,
    government: "guided",
    population: 510_000_000,
    gdp: 6.4e14,
    gdpGrowth: 4.8,
    inflation: 2.1,
    interestRate: 3.4,
    unemployment: 5.3,
    corpTax: 20,
    incomeTax: 22,
    propertyTax: 0.9,
    vat: 13,
    debt: 4.1e14,
    techLevel: 79,
    aiAdoption: 61,
    infrastructure: 84,
    educationIndex: 76,
    healthcareIndex: 70,
    housingIndex: 58,
    businessFreedom: 52,
    crimeIndex: 22,
    tariff: 9,
    tradeBalance: 2.8e13,
    policy: { ...centrist(), business: 55, technology: 85, trade: 40, spending: 70 },
    rulingPartyId: "zhenhua_harmony",
    headOfGov: "Wei Shanyuan",
    electionYear: 2031,
    conMember: true,
    councilSeat: true,
    blocs: ["East Arc", "Tech Accord"],
    color: "#ef9a9a",
    map: { x: 68, y: 26, w: 16, h: 14 },
  },
  {
    id: "solara",
    name: "Solaran Republic",
    adjective: "Solaran",
    capital: "Cinderport",
    currency: { code: "SLR", name: "Solaran Sun", symbol: "☉" },
    fx: 22,
    government: "presidential",
    population: 38_000_000,
    gdp: 9.4e13,
    gdpGrowth: 3.2,
    inflation: 5.5,
    interestRate: 7.25,
    unemployment: 8.4,
    corpTax: 27,
    incomeTax: 28,
    propertyTax: 1.0,
    vat: 15,
    debt: 5.1e13,
    techLevel: 48,
    aiAdoption: 12,
    infrastructure: 46,
    educationIndex: 49,
    healthcareIndex: 44,
    housingIndex: 48,
    businessFreedom: 55,
    crimeIndex: 51,
    tariff: 12,
    tradeBalance: 6.4e12,
    policy: { ...centrist(), environment: 35, trade: 45, business: 58 },
    rulingPartyId: "solara_desert",
    headOfGov: "Rami Al-Nour",
    electionYear: 2028,
    conMember: true,
    councilSeat: true,
    blocs: ["Energy Forum"],
    color: "#f4c38b",
    map: { x: 46, y: 54, w: 13, h: 11 },
  },
  {
    id: "kairos",
    name: "Kairos City-State",
    adjective: "Kairan",
    capital: "Kairos",
    currency: { code: "KRS", name: "Kairan Shield", symbol: "Κ" },
    fx: 62,
    government: "parliamentary",
    population: 6_200_000,
    gdp: 5.8e13,
    gdpGrowth: 3.4,
    inflation: 2.0,
    interestRate: 3.6,
    unemployment: 2.8,
    corpTax: 17,
    incomeTax: 20,
    propertyTax: 0.4,
    vat: 7,
    debt: 1.1e13,
    techLevel: 90,
    aiAdoption: 58,
    infrastructure: 93,
    educationIndex: 88,
    healthcareIndex: 86,
    housingIndex: 62,
    businessFreedom: 94,
    crimeIndex: 12,
    tariff: 0,
    tradeBalance: 3.1e12,
    policy: { ...centrist(), business: 88, tax: 28, trade: 92, immigration: 70 },
    rulingPartyId: "kairos_open",
    headOfGov: "Sera Tan",
    electionYear: 2027,
    conMember: true,
    councilSeat: false,
    blocs: ["Tech Accord", "Trade Circle"],
    color: "#c4b5fd",
    map: { x: 72, y: 48, w: 7, h: 6 },
  },
  {
    id: "meridia",
    name: "Meridian Isles",
    adjective: "Meridian",
    capital: "Pearl Bay",
    currency: { code: "MRD", name: "Meridian Florin", symbol: "ƒ" },
    fx: 31,
    government: "parliamentary",
    population: 8_800_000,
    gdp: 1.6e13,
    gdpGrowth: 2.8,
    inflation: 3.6,
    interestRate: 5.0,
    unemployment: 10.2,
    corpTax: 24,
    incomeTax: 26,
    propertyTax: 1.2,
    vat: 16,
    debt: 9.4e12,
    techLevel: 44,
    aiAdoption: 10,
    infrastructure: 51,
    educationIndex: 58,
    healthcareIndex: 52,
    housingIndex: 55,
    businessFreedom: 61,
    crimeIndex: 38,
    tariff: 7,
    tradeBalance: -8e11,
    policy: { ...centrist(), environment: 68, immigration: 40, infrastructure: 58 },
    rulingPartyId: "meridia_tide",
    headOfGov: "Imani Cole",
    electionYear: 2026,
    conMember: true,
    councilSeat: false,
    blocs: ["Island Forum", "Green Compact"],
    color: "#67e8f9",
    map: { x: 22, y: 62, w: 11, h: 8 },
  },
  {
    id: "ostara",
    name: "Republic of Ostara",
    adjective: "Ostaran",
    capital: "Veles",
    currency: { code: "OST", name: "Ostaran Zlot", symbol: "zł" },
    fx: 21,
    government: "presidential",
    population: 27_000_000,
    gdp: 4.1e13,
    gdpGrowth: 3.0,
    inflation: 7.8,
    interestRate: 9.5,
    unemployment: 8.8,
    corpTax: 19,
    incomeTax: 27,
    propertyTax: 0.7,
    vat: 20,
    debt: 2.9e13,
    techLevel: 57,
    aiAdoption: 18,
    infrastructure: 55,
    educationIndex: 66,
    healthcareIndex: 60,
    housingIndex: 57,
    businessFreedom: 63,
    crimeIndex: 36,
    tariff: 6,
    tradeBalance: -1.4e12,
    policy: { ...centrist(), tax: 38, business: 66, welfare: 42 },
    rulingPartyId: "ostara_renewal",
    headOfGov: "Katarina Vossik",
    electionYear: 2028,
    conMember: true,
    councilSeat: false,
    blocs: ["Heartland Pact"],
    color: "#86efac",
    map: { x: 44, y: 30, w: 11, h: 10 },
  },
  {
    id: "palmyra",
    name: "Palmyran Confederation",
    adjective: "Palmyran",
    capital: "Qasr",
    currency: { code: "PLM", name: "Palmyran Dinar", symbol: "ḏ" },
    fx: 220,
    government: "monarchy",
    population: 9_600_000,
    gdp: 1.02e14,
    gdpGrowth: 2.4,
    inflation: 2.8,
    interestRate: 5.5,
    unemployment: 6.1,
    corpTax: 15,
    incomeTax: 0,
    propertyTax: 0.2,
    vat: 5,
    debt: 1.8e13,
    techLevel: 60,
    aiAdoption: 22,
    infrastructure: 72,
    educationIndex: 64,
    healthcareIndex: 68,
    housingIndex: 60,
    businessFreedom: 70,
    crimeIndex: 24,
    tariff: 5,
    tradeBalance: 1.9e13,
    policy: { ...centrist(), tax: 18, business: 75, welfare: 40, immigration: 30 },
    rulingPartyId: "palmyra_house",
    headOfGov: "Prince Idris Al-Qasr",
    electionYear: 2035,
    conMember: true,
    councilSeat: false,
    blocs: ["Energy Forum", "Trade Circle"],
    color: "#fde68a",
    map: { x: 56, y: 50, w: 10, h: 9 },
  },
];

export const CITY_DEFS: Omit<City, "demand" | "jobs">[] = [
  { id: "navpura", name: "Navpura", countryId: "indara", population: 18_400_000, avgWage: 720000, propertyIndex: 100, rentIndex: 100, infrastructure: 70, schools: 74, transit: 68, businessActivity: 80, housingSupply: 72, industrial: 55, tech: 62, tourism: 40, x: 58, y: 46 },
  { id: "surajgarh", name: "Surajgarh", countryId: "indara", population: 14_200_000, avgWage: 980000, propertyIndex: 128, rentIndex: 122, infrastructure: 78, schools: 80, transit: 76, businessActivity: 92, housingSupply: 60, industrial: 40, tech: 58, tourism: 50, x: 54, y: 44 },
  { id: "techpur", name: "Techpur", countryId: "indara", population: 9_100_000, avgWage: 1100000, propertyIndex: 140, rentIndex: 130, infrastructure: 75, schools: 82, transit: 70, businessActivity: 88, housingSupply: 58, industrial: 35, tech: 90, tourism: 30, x: 56, y: 48 },
  { id: "coastalin", name: "Coastalin", countryId: "indara", population: 6_400_000, avgWage: 640000, propertyIndex: 88, rentIndex: 90, infrastructure: 62, schools: 60, transit: 64, businessActivity: 70, housingSupply: 80, industrial: 72, tech: 40, tourism: 55, x: 50, y: 50 },
  { id: "lumen", name: "Lumen", countryId: "aurelia", population: 9_800_000, avgWage: 4200000, propertyIndex: 210, rentIndex: 200, infrastructure: 90, schools: 88, transit: 92, businessActivity: 95, housingSupply: 52, industrial: 30, tech: 92, tourism: 70, x: 18, y: 30 },
  { id: "westport", name: "Westport", countryId: "aurelia", population: 4_200_000, avgWage: 3600000, propertyIndex: 180, rentIndex: 170, infrastructure: 86, schools: 84, transit: 80, businessActivity: 84, housingSupply: 60, industrial: 48, tech: 70, tourism: 62, x: 12, y: 32 },
  { id: "highridge", name: "Highridge", countryId: "aurelia", population: 2_100_000, avgWage: 3900000, propertyIndex: 240, rentIndex: 210, infrastructure: 88, schools: 94, transit: 70, businessActivity: 78, housingSupply: 45, industrial: 18, tech: 80, tourism: 40, x: 20, y: 26 },
  { id: "kestrel", name: "Kestrel", countryId: "vardania", population: 5_600_000, avgWage: 980000, propertyIndex: 70, rentIndex: 68, infrastructure: 55, schools: 58, transit: 52, businessActivity: 64, housingSupply: 78, industrial: 80, tech: 40, tourism: 22, x: 38, y: 24 },
  { id: "ironbend", name: "Ironbend", countryId: "vardania", population: 3_200_000, avgWage: 860000, propertyIndex: 54, rentIndex: 52, infrastructure: 48, schools: 50, transit: 46, businessActivity: 58, housingSupply: 85, industrial: 92, tech: 28, tourism: 12, x: 34, y: 28 },
  { id: "havnstad", name: "Havnstad", countryId: "nordmark", population: 1_900_000, avgWage: 3100000, propertyIndex: 190, rentIndex: 175, infrastructure: 94, schools: 96, transit: 90, businessActivity: 76, housingSupply: 50, industrial: 30, tech: 78, tourism: 66, x: 44, y: 10 },
  { id: "fjellheim", name: "Fjellheim", countryId: "nordmark", population: 620000, avgWage: 2800000, propertyIndex: 150, rentIndex: 140, infrastructure: 88, schools: 92, transit: 70, businessActivity: 58, housingSupply: 62, industrial: 40, tech: 60, tourism: 80, x: 40, y: 12 },
  { id: "dongcheng", name: "Dongcheng", countryId: "zhenhua", population: 22_000_000, avgWage: 1400000, propertyIndex: 160, rentIndex: 150, infrastructure: 88, schools: 80, transit: 94, businessActivity: 90, housingSupply: 55, industrial: 70, tech: 85, tourism: 48, x: 74, y: 30 },
  { id: "southhaven", name: "Southhaven", countryId: "zhenhua", population: 12_400_000, avgWage: 1100000, propertyIndex: 110, rentIndex: 108, infrastructure: 80, schools: 72, transit: 84, businessActivity: 82, housingSupply: 70, industrial: 88, tech: 60, tourism: 30, x: 70, y: 34 },
  { id: "cinderport", name: "Cinderport", countryId: "solara", population: 3_400_000, avgWage: 920000, propertyIndex: 64, rentIndex: 60, infrastructure: 50, schools: 48, transit: 44, businessActivity: 60, housingSupply: 76, industrial: 70, tech: 30, tourism: 35, x: 48, y: 56 },
  { id: "oasis", name: "Oasis Reach", countryId: "solara", population: 1_100_000, avgWage: 1040000, propertyIndex: 80, rentIndex: 72, infrastructure: 58, schools: 52, transit: 40, businessActivity: 55, housingSupply: 68, industrial: 40, tech: 25, tourism: 55, x: 52, y: 52 },
  { id: "kairos", name: "Kairos", countryId: "kairos", population: 5_800_000, avgWage: 3600000, propertyIndex: 260, rentIndex: 250, infrastructure: 96, schools: 90, transit: 98, businessActivity: 99, housingSupply: 40, industrial: 22, tech: 94, tourism: 60, x: 74, y: 50 },
  { id: "pearlbay", name: "Pearl Bay", countryId: "meridia", population: 1_400_000, avgWage: 780000, propertyIndex: 95, rentIndex: 100, infrastructure: 60, schools: 64, transit: 50, businessActivity: 58, housingSupply: 70, industrial: 20, tech: 28, tourism: 92, x: 24, y: 64 },
  { id: "veles", name: "Veles", countryId: "ostara", population: 2_800_000, avgWage: 860000, propertyIndex: 62, rentIndex: 60, infrastructure: 58, schools: 70, transit: 55, businessActivity: 62, housingSupply: 74, industrial: 60, tech: 48, tourism: 36, x: 46, y: 32 },
  { id: "qasr", name: "Qasr", countryId: "palmyra", population: 2_200_000, avgWage: 2400000, propertyIndex: 175, rentIndex: 160, infrastructure: 80, schools: 72, transit: 70, businessActivity: 74, housingSupply: 58, industrial: 30, tech: 50, tourism: 64, x: 58, y: 52 },
];

export const PARTY_DEFS: { id: string; countryId: string; name: string; color: string; leader: string; seats: number; popularity: number; platform: PolicyVector }[] = [
  { id: "indara_unity", countryId: "indara", name: "Unity Front", color: "#e8b86d", leader: "Meera Halder", seats: 241, popularity: 38, platform: { ...centrist(), technology: 70, business: 64, welfare: 46 } },
  { id: "indara_people", countryId: "indara", name: "People's Mandala", color: "#fb7185", leader: "Arjun Sethi", seats: 188, popularity: 31, platform: { ...centrist(), welfare: 74, tax: 68, business: 38 } },
  { id: "indara_green", countryId: "indara", name: "Monsoon Greens", color: "#34d399", leader: "Nila Rao", seats: 62, popularity: 14, platform: { ...centrist(), environment: 88, technology: 60, infrastructure: 62 } },
  { id: "indara_liberty", countryId: "indara", name: "Liberty League", color: "#93c5fd", leader: "Vikram D'Souza", seats: 41, popularity: 9, platform: { ...centrist(), tax: 28, business: 82, welfare: 30 } },
  { id: "aurelia_horizon", countryId: "aurelia", name: "Horizon Party", color: "#6ea8ff", leader: "Julian Voss", seats: 228, popularity: 41, platform: { ...centrist(), business: 72, technology: 82 } },
  { id: "aurelia_labor", countryId: "aurelia", name: "Civic Labor", color: "#f87171", leader: "Maren Holt", seats: 190, popularity: 36, platform: { ...centrist(), welfare: 76, tax: 64 } },
  { id: "aurelia_free", countryId: "aurelia", name: "Free Commonwealth", color: "#fbbf24", leader: "Owen Drake", seats: 72, popularity: 14, platform: { ...centrist(), tax: 30, immigration: 35 } },
  { id: "vardania_forge", countryId: "vardania", name: "Forge Alliance", color: "#d97757", leader: "Anton Reznik", seats: 160, popularity: 40, platform: { ...centrist(), infrastructure: 78, business: 66 } },
  { id: "vardania_soil", countryId: "vardania", name: "Soil & Steel", color: "#a3e635", leader: "Irina Volkov", seats: 120, popularity: 32, platform: { ...centrist(), welfare: 62, trade: 35 } },
  { id: "nordmark_civic", countryId: "nordmark", name: "Civic Alliance", color: "#7dd3c7", leader: "Elsa Lindholm", seats: 92, popularity: 44, platform: { ...centrist(), welfare: 80, environment: 78 } },
  { id: "nordmark_market", countryId: "nordmark", name: "Market Moderates", color: "#fda4af", leader: "Henrik Blaalid", seats: 71, popularity: 33, platform: { ...centrist(), tax: 45, business: 70 } },
  { id: "zhenhua_harmony", countryId: "zhenhua", name: "Harmony Path", color: "#ef9a9a", leader: "Wei Shanyuan", seats: 2100, popularity: 62, platform: { ...centrist(), technology: 86, spending: 72 } },
  { id: "zhenhua_reform", countryId: "zhenhua", name: "Reform Circles", color: "#fdba74", leader: "Lin Qiaoran", seats: 420, popularity: 22, platform: { ...centrist(), business: 70, tax: 40 } },
  { id: "solara_desert", countryId: "solara", name: "Desert Concord", color: "#f4c38b", leader: "Rami Al-Nour", seats: 118, popularity: 39, platform: { ...centrist(), trade: 40, tax: 45 } },
  { id: "solara_new", countryId: "solara", name: "New Sun Movement", color: "#38bdf8", leader: "Lila Hassan", seats: 96, popularity: 34, platform: { ...centrist(), environment: 70, welfare: 62 } },
  { id: "kairos_open", countryId: "kairos", name: "Open Port Party", color: "#c4b5fd", leader: "Sera Tan", seats: 48, popularity: 52, platform: { ...centrist(), business: 88, trade: 90 } },
  { id: "kairos_fair", countryId: "kairos", name: "Fair City", color: "#86efac", leader: "Daniel Okoye", seats: 36, popularity: 38, platform: { ...centrist(), housing: 78, welfare: 64 } },
  { id: "meridia_tide", countryId: "meridia", name: "Tide Coalition", color: "#67e8f9", leader: "Imani Cole", seats: 28, popularity: 42, platform: { ...centrist(), environment: 72, infrastructure: 60 } },
  { id: "meridia_harvest", countryId: "meridia", name: "Harvest Party", color: "#bef264", leader: "Paolo Reyes", seats: 22, popularity: 33, platform: { ...centrist(), welfare: 60, trade: 40 } },
  { id: "ostara_renewal", countryId: "ostara", name: "Renewal Bloc", color: "#86efac", leader: "Katarina Vossik", seats: 110, popularity: 37, platform: { ...centrist(), business: 68, tax: 36 } },
  { id: "ostara_social", countryId: "ostara", name: "Social Ostara", color: "#f9a8d4", leader: "Marek Holub", seats: 98, popularity: 34, platform: { ...centrist(), welfare: 74, tax: 62 } },
  { id: "palmyra_house", countryId: "palmyra", name: "House Concord", color: "#fde68a", leader: "Prince Idris Al-Qasr", seats: 80, popularity: 58, platform: { ...centrist(), tax: 18, business: 78 } },
  { id: "palmyra_civic", countryId: "palmyra", name: "Civic Majlis", color: "#a5b4fc", leader: "Noor El-Amin", seats: 40, popularity: 26, platform: { ...centrist(), welfare: 55, education: 70 } },
];

export const FIRST_NAMES = [
  "Asha", "Rohan", "Meera", "Julian", "Sera", "Anton", "Nila", "Owen", "Imani", "Wei",
  "Elsa", "Rami", "Katarina", "Daniel", "Lila", "Vikram", "Maren", "Arjun", "Noor", "Henrik",
  "Priya", "Leo", "Anika", "Mateo", "Zara", "Noah", "Diya", "Kai", "Sofia", "Dev",
];
export const LAST_NAMES = [
  "Halder", "Voss", "Tan", "Reznik", "Cole", "Lindholm", "Sethi", "Okoye", "Al-Nour", "Qiaoran",
  "Rao", "Holt", "D'Souza", "Reyes", "El-Amin", "Blaalid", "Holub", "Hassan", "Drake", "Volkov",
  "Menon", "Park", "Iyer", "Nielsen", "Costa", "Sharma", "Berg", "Kapoor", "Silva", "Khan",
];

export const COMPANY_PREFIX = [
  "North", "Apex", "Lumen", "Iron", "Nimbus", "Harbor", "Quantum", "Cedar", "Atlas", "Silk",
  "Vesper", "Helio", "Kite", "Forge", "Pearl", "Orbit", "Summit", "River", "Prism", "Amber",
];
export const COMPANY_SUFFIX = [
  "Systems", "Holdings", "Labs", "Dynamics", "Capital", "Media", "Energy", "Works", "Logistics",
  "Foods", "Estates", "Health", "Bank", "Mutual", "Robotics", "Cloud", "Studios", "Motors", "Mining", "Retail",
];

export const JOB_RANKS: { rank: number; title: (ind: string) => string; mult: number; edu: number; exp: number }[] = [
  { rank: 1, title: (i) => `Intern, ${i}`, mult: 0.25, edu: 1, exp: 0 },
  { rank: 2, title: (i) => `Junior ${i} Associate`, mult: 0.55, edu: 2, exp: 0 },
  { rank: 3, title: (i) => `${i} Specialist`, mult: 0.85, edu: 2, exp: 2 },
  { rank: 4, title: (i) => `Senior ${i} Specialist`, mult: 1.15, edu: 3, exp: 4 },
  { rank: 5, title: (i) => `${i} Lead`, mult: 1.5, edu: 3, exp: 6 },
  { rank: 6, title: (i) => `${i} Manager`, mult: 1.9, edu: 3, exp: 8 },
  { rank: 7, title: (i) => `Director of ${i}`, mult: 2.6, edu: 4, exp: 11 },
  { rank: 8, title: (i) => `VP of ${i}`, mult: 3.6, edu: 4, exp: 14 },
  { rank: 9, title: (i) => `Chief ${i} Officer`, mult: 5.2, edu: 4, exp: 16 },
  { rank: 10, title: () => `Chief Executive Officer`, mult: 8.5, edu: 4, exp: 18 },
];

export const INDUSTRY_JOB_LABEL: Record<Industry, string> = {
  technology: "Technology",
  ai: "AI",
  software: "Software",
  gaming: "Game",
  retail: "Retail",
  ecommerce: "E-commerce",
  restaurants: "Hospitality",
  hotels: "Hotel",
  construction: "Construction",
  manufacturing: "Plant",
  logistics: "Logistics",
  energy: "Energy",
  agriculture: "Agri",
  education: "Education",
  media: "Media",
  advertising: "Advertising",
  finance: "Finance",
  insurance: "Insurance",
  banking: "Banking",
  realestate: "Property",
  entertainment: "Entertainment",
  healthcare: "Clinical",
  legal: "Legal",
  cybersecurity: "Security",
  robotics: "Robotics",
  telecom: "Network",
  mining: "Mining",
  tourism: "Tourism",
  casino: "Casino",
  research: "Research",
};

export function makeJobsForCity(city: City, country: Country, n = 18): JobListing[] {
  const jobs: JobListing[] = [];
  const inds = INDUSTRIES;
  for (let i = 0; i < n; i++) {
    const ind = inds[(i * 3 + city.name.length) % inds.length]!;
    const rank = JOB_RANKS[1 + (i % 8)]!;
    const base = city.avgWage * ind.wage * rank.mult;
    const demand = Math.max(10, Math.min(100, 55 + city.businessActivity * 0.3 - country.unemployment * 2 + (i % 7) * 3));
    jobs.push({
      id: `job_${city.id}_${ind.id}_${rank.rank}_${i}`,
      title: rank.rank === 10 ? "Chief Executive Officer" : rank.title(INDUSTRY_JOB_LABEL[ind.id]),
      industry: ind.id,
      rank: rank.rank,
      countryId: country.id,
      cityId: city.id,
      employer: `${COMPANY_PREFIX[i % COMPANY_PREFIX.length]} ${COMPANY_SUFFIX[(i + 4) % COMPANY_SUFFIX.length]}`,
      salary: Math.round(base * (0.9 + (i % 5) * 0.04)),
      hours: rank.rank >= 8 ? 55 : rank.rank <= 2 ? 35 : 42,
      educationMin: rank.edu,
      experienceMin: rank.exp,
      skills: Object.fromEntries(ind.skills.filter((s) => s).map((s, idx) => [s, 20 + rank.rank * 6 - idx * 4])),
      security: 40 + (10 - rank.rank) * 4,
      bonusPct: rank.rank >= 6 ? 15 : 5,
      benefits: 8 + rank.rank,
      demand,
      type: i % 9 === 0 ? "contract" : i % 7 === 0 ? "part" : "full",
    });
  }
  return jobs;
}

export const FREELANCE_GIGS: { industry: Industry; title: string }[] = [
  { industry: "software", title: "Contract developer" },
  { industry: "ai", title: "AI prototype consultant" },
  { industry: "advertising", title: "Brand designer" },
  { industry: "media", title: "Freelance journalist" },
  { industry: "education", title: "Online tutor" },
  { industry: "realestate", title: "Property scout" },
  { industry: "finance", title: "Bookkeeping contractor" },
  { industry: "advertising", title: "Growth marketer" },
  { industry: "legal", title: "Document reviewer" },
  { industry: "construction", title: "Site supervisor" },
];

export const ACHIEVEMENTS: { id: string; name: string; desc: string }[] = [
  { id: "doctor", name: "Doctorate", desc: "Complete a PhD." },
  { id: "developer", name: "Developer", desc: "Complete a property development." },
  { id: "tax_honest", name: "Model Taxpayer", desc: "File five honest tax returns." },
  { id: "broker_firm", name: "Wall Street", desc: "Found a brokerage firm." },
  { id: "married", name: "Tied the Knot", desc: "Get married." },
  { id: "parent", name: "Parenthood", desc: "Have or adopt a child." },
  { id: "centenarian", name: "Centenarian", desc: "Live to 100." },
  { id: "pilot", name: "Licensed to Fly", desc: "Earn a pilot licence." },
  { id: "wings", name: "Wings", desc: "Buy your first aircraft." },
  { id: "fleet", name: "Fleet Owner", desc: "Own five aircraft at once." },
  { id: "yacht", name: "Sea Legs", desc: "Buy a yacht." },
  { id: "petrolhead", name: "Petrolhead", desc: "Buy a supercar or hypercar." },
  { id: "globetrotter", name: "Globetrotter", desc: "Visit every country on the map." },
  { id: "takeover", name: "Corporate Raider", desc: "Take control of a company through a tender offer." },
  { id: "cash_10k", name: "First ₹10,000", desc: "Hold ₹10,000 cash." },
  { id: "cash_1l", name: "First ₹1 Lakh", desc: "Hold ₹1 lakh cash." },
  { id: "cash_1cr", name: "First ₹1 Crore", desc: "Reach ₹1 crore net worth." },
  { id: "first_job", name: "First Paycheque", desc: "Accept your first job." },
  { id: "first_biz", name: "Founder", desc: "Found a company." },
  { id: "profit_month", name: "In the Black", desc: "A company of yours posts a profitable month." },
  { id: "first_prop", name: "Keys", desc: "Buy your first property." },
  { id: "rental", name: "Landlord", desc: "Collect rental income." },
  { id: "grant", name: "Public Backing", desc: "Win a government grant." },
  { id: "investor", name: "Someone Believes", desc: "Raise outside investment." },
  { id: "million", name: "Millionaire", desc: "Net worth of ₹1 crore+ (ten million rupees)." },
  { id: "ten_cr", name: "Ten Crore Club", desc: "Net worth of ₹10 crore." },
  { id: "hundred_cr", name: "Century", desc: "Net worth of ₹100 crore." },
  { id: "billion", name: "Billionaire", desc: "Net worth of ₹1,000 crore." },
  { id: "ipo", name: "Ring the Bell", desc: "Take a company public." },
  { id: "ceo", name: "Corner Office", desc: "Become CEO of a company." },
  { id: "banker", name: "Bank Owner", desc: "Found or acquire a bank." },
  { id: "ai_founder", name: "Model Maker", desc: "Found an AI company." },
  { id: "party", name: "Party Founder", desc: "Create a political party." },
  { id: "elected", name: "The People's Choice", desc: "Win an election." },
  { id: "head", name: "Head of Government", desc: "Lead a country." },
  { id: "media", name: "Media Empire", desc: "Own multiple media outlets." },
  { id: "intl", name: "International Corporation", desc: "Operate in 3+ countries." },
  { id: "rebuild", name: "From the Ashes", desc: "Recover after net worth going negative." },
  { id: "graduate", name: "Graduate", desc: "Complete a university degree." },
  { id: "casino_tycoon", name: "House Edge", desc: "Own a casino." },
  { id: "dynasty", name: "Dynasty", desc: "Continue as an heir." },
  { id: "con", name: "World Stage", desc: "Address the Concord of Nations." },
  { id: "citizen", name: "New Passport", desc: "Gain a second citizenship." },
  { id: "skill_master", name: "Craft Master", desc: "Reach 90 in any skill." },
  { id: "challenge", name: "Prover", desc: "Complete a self-chosen challenge." },
  { id: "oracle", name: "Oracle", desc: "Win three market forecasts." },
  { id: "cabinet", name: "Inner Circle", desc: "Employ a full staff of advisors." },
  { id: "auctioneer", name: "Vulture", desc: "Win a distressed asset at auction." },
  { id: "builder", name: "Public Works", desc: "Complete a national infrastructure project." },
  { id: "statecraft", name: "The Levers", desc: "Pass a law of your own." },
  { id: "victory", name: "Triumph", desc: "Win a war." },
  { id: "conqueror", name: "Conqueror", desc: "Annex territory from another country." },
  { id: "dictator", name: "Supreme", desc: "Replace the constitution with personal rule." },
];

export const BACKGROUNDS = [
  { id: "working", name: "Working family", wealth: 18000, edu: 2, note: "Modest means, strong work ethic." },
  { id: "middle", name: "Middle class", wealth: 45000, edu: 2, note: "Stable household, ordinary start." },
  { id: "academic", name: "Academic household", wealth: 32000, edu: 3, note: "Books over capital." },
  { id: "immigrant", name: "New arrival", wealth: 12000, edu: 2, note: "Start over in a new country." },
  { id: "merchant", name: "Merchant family", wealth: 120000, edu: 2, note: "Trade in the blood." },
  { id: "political", name: "Political household", wealth: 80000, edu: 3, note: "Dinner-table debates." },
  { id: "rural", name: "Rural town", wealth: 8000, edu: 1, note: "Far from the capital." },
];

export const MODES: { id: import("./types").GameMode; name: string; blurb: string; wealth: number; age: number; edu: number }[] = [
  { id: "normal", name: "Normal Life", blurb: "Balanced start. Age 18, a little cash, a whole world.", wealth: 28000, age: 18, edu: 2 },
  { id: "zero", name: "Zero to Empire", blurb: "Almost nothing. Build everything.", wealth: 2500, age: 18, edu: 2 },
  { id: "rich", name: "Rich Family", blurb: "Inherit capital, a house, and expectations.", wealth: 5e7, age: 18, edu: 3 },
  { id: "entrepreneur", name: "Entrepreneur", blurb: "Young founder energy, a small war chest.", wealth: 150000, age: 22, edu: 3 },
  { id: "politician", name: "Politician", blurb: "Law degree, connections, public hunger.", wealth: 90000, age: 28, edu: 4 },
  { id: "investor", name: "Investor", blurb: "Capital-market focused, ready to allocate.", wealth: 5e6, age: 30, edu: 4 },
  { id: "crime", name: "Underground", blurb: "High risk fictional path. Heat from day one.", wealth: 8000, age: 19, edu: 1 },
  { id: "random", name: "Random Life", blurb: "Completely shuffled start.", wealth: 0, age: 18, edu: 2 },
  { id: "leader", name: "Country Leader", blurb: "Already inside the machine of government.", wealth: 2e6, age: 46, edu: 4 },
  { id: "sandbox", name: "World Sandbox", blurb: "Maximum simulation depth and visibility.", wealth: 1e6, age: 25, edu: 3 },
];

export const SOCIAL_PLATFORMS = [
  { id: "pulse", name: "Pulse", vibe: "short posts" },
  { id: "lumen", name: "LumenCast", vibe: "video" },
  { id: "folio", name: "Folio", vibe: "long essays" },
  { id: "hive", name: "Hive", vibe: "communities" },
];

export const MEDIA_KINDS = ["Newspaper", "News site", "TV channel", "Magazine", "Podcast network", "Digital media"];

export const BILL_TOPICS = [
  { id: "corp_tax", label: "Corporate tax", key: "tax" as const },
  { id: "income_tax", label: "Income tax", key: "tax" as const },
  { id: "education", label: "Education funding", key: "education" as const },
  { id: "healthcare", label: "Healthcare", key: "healthcare" as const },
  { id: "infra", label: "Infrastructure", key: "infrastructure" as const },
  { id: "tech", label: "Technology grants", key: "technology" as const },
  { id: "housing", label: "Housing", key: "housing" as const },
  { id: "environment", label: "Environment", key: "environment" as const },
  { id: "crime", label: "Public safety", key: "crime" as const },
  { id: "trade", label: "Trade tariffs", key: "trade" as const },
];

export function emptySkills(): Record<string, number> {
  const s: Record<string, number> = {};
  for (const k of SKILLS) s[k.id] = 5;
  return s;
}
